## Tensors

In [1]:
# Tensors are data structures similar to numpy nd-array
import torch
import numpy as np

In [2]:
# initializing a tensor

x = [[1,2,3],[2,3,4]]
x_data = torch.tensor(x)

In [3]:
x_data

tensor([[1, 2, 3],
        [2, 3, 4]])

In [4]:
type(x_data)

torch.Tensor

In [5]:
# from numpy array
np_array = np.array(x)
tens = torch.from_numpy(np_array)

In [6]:
tens

tensor([[1, 2, 3],
        [2, 3, 4]], dtype=torch.int32)

In [7]:
# from another tensor
x_ones = torch.ones_like(x_data)
x_ones
# x_ones retains the properties of x_data

tensor([[1, 1, 1],
        [1, 1, 1]])

In [8]:
x_rand = torch.rand_like(x_data,dtype=torch.float)
x_rand

tensor([[0.7998, 0.6212, 0.5340],
        [0.5504, 0.2564, 0.4584]])

In [9]:
x_rand.shape

torch.Size([2, 3])

In [10]:
shape = (2,4,)
rand_tensor = torch.rand(shape)
print(f"random tensor: {rand_tensor} \n")
ones_like_tensor = torch.ones_like(rand_tensor)
print(f"ones_like tensor: {ones_like_tensor} \n")
ones_tensor = torch.ones(shape)
print(f"ones tensor: {ones_tensor} \n")
zeros_like_tensor = torch.zeros_like(ones_tensor)
print(f"zeros_like tensor: {zeros_like_tensor} \n")
zeros_tensor = torch.zeros(shape)
print(f"zeros tensor: {zeros_tensor} \n")

random tensor: tensor([[0.9587, 0.5559, 0.3803, 0.8532],
        [0.9931, 0.3078, 0.2555, 0.5595]]) 

ones_like tensor: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

ones tensor: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

zeros_like tensor: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 

zeros tensor: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 



### Attributes of a Tensor

In [11]:
tensor = torch.rand(13,14)
tensor

tensor([[0.0996, 0.2811, 0.3562, 0.6368, 0.8802, 0.9601, 0.7112, 0.5832, 0.5959,
         0.8479, 0.6744, 0.6863, 0.7849, 0.7669],
        [0.0414, 0.6044, 0.2702, 0.8342, 0.6036, 0.0452, 0.0224, 0.1510, 0.2966,
         0.0894, 0.0042, 0.7061, 0.5662, 0.8710],
        [0.8644, 0.0541, 0.6763, 0.2708, 0.8131, 0.1226, 0.1341, 0.1980, 0.4425,
         0.3688, 0.6767, 0.6336, 0.7153, 0.0661],
        [0.5555, 0.1675, 0.0586, 0.5774, 0.1785, 0.3513, 0.4526, 0.4149, 0.2665,
         0.5032, 0.7312, 0.6522, 0.7385, 0.7984],
        [0.1988, 0.6426, 0.3554, 0.7942, 0.4537, 0.7852, 0.2483, 0.9153, 0.3306,
         0.7045, 0.6144, 0.3344, 0.7124, 0.4184],
        [0.8903, 0.7750, 0.1120, 0.4298, 0.7757, 0.4645, 0.4057, 0.8410, 0.2942,
         0.8072, 0.2647, 0.4979, 0.6713, 0.4582],
        [0.0253, 0.4372, 0.7700, 0.6587, 0.9909, 0.8835, 0.8096, 0.2442, 0.6259,
         0.4962, 0.2831, 0.3474, 0.1457, 0.0101],
        [0.1358, 0.0470, 0.5990, 0.3937, 0.8479, 0.1305, 0.3448, 0.9331, 0.1950,
  

In [12]:
print(f"shape of the tensor: {tensor.shape} \n")
print(f"datatype of the tensor: {tensor.dtype} \n")
print(f"location of the tensor: {tensor.device} \n")

shape of the tensor: torch.Size([13, 14]) 

datatype of the tensor: torch.float32 

location of the tensor: cpu 



### Operations on Tensors

In [13]:
# moving tensors to GPU
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

### Standard numpy and other operations (slicing, indexing etc..)

In [14]:
tensor = torch.rand(3,5)
tensor

tensor([[0.5504, 0.5260, 0.8353, 0.5505, 0.3775],
        [0.5664, 0.6632, 0.2959, 0.2655, 0.8795],
        [0.8190, 0.4385, 0.6086, 0.9412, 0.6157]])

In [15]:
tensor[0] # first row

tensor([0.5504, 0.5260, 0.8353, 0.5505, 0.3775])

In [16]:
# first column
tensor[:,0]

tensor([0.5504, 0.5664, 0.8190])

In [17]:
tensor[0,:] #first row

tensor([0.5504, 0.5260, 0.8353, 0.5505, 0.3775])

In [18]:
# first column
tensor[:,1]

tensor([0.5260, 0.6632, 0.4385])

In [19]:
print(tensor)

tensor([[0.5504, 0.5260, 0.8353, 0.5505, 0.3775],
        [0.5664, 0.6632, 0.2959, 0.2655, 0.8795],
        [0.8190, 0.4385, 0.6086, 0.9412, 0.6157]])


In [20]:
# joining tensors 

t1 = torch.cat([tensor,tensor,tensor],dim=1)
t1

tensor([[0.5504, 0.5260, 0.8353, 0.5505, 0.3775, 0.5504, 0.5260, 0.8353, 0.5505,
         0.3775, 0.5504, 0.5260, 0.8353, 0.5505, 0.3775],
        [0.5664, 0.6632, 0.2959, 0.2655, 0.8795, 0.5664, 0.6632, 0.2959, 0.2655,
         0.8795, 0.5664, 0.6632, 0.2959, 0.2655, 0.8795],
        [0.8190, 0.4385, 0.6086, 0.9412, 0.6157, 0.8190, 0.4385, 0.6086, 0.9412,
         0.6157, 0.8190, 0.4385, 0.6086, 0.9412, 0.6157]])

In [21]:
tlist = []
for i in range(0,len(tensor)):
    tlist.append(tensor)

In [22]:
tlist

[tensor([[0.5504, 0.5260, 0.8353, 0.5505, 0.3775],
         [0.5664, 0.6632, 0.2959, 0.2655, 0.8795],
         [0.8190, 0.4385, 0.6086, 0.9412, 0.6157]]),
 tensor([[0.5504, 0.5260, 0.8353, 0.5505, 0.3775],
         [0.5664, 0.6632, 0.2959, 0.2655, 0.8795],
         [0.8190, 0.4385, 0.6086, 0.9412, 0.6157]]),
 tensor([[0.5504, 0.5260, 0.8353, 0.5505, 0.3775],
         [0.5664, 0.6632, 0.2959, 0.2655, 0.8795],
         [0.8190, 0.4385, 0.6086, 0.9412, 0.6157]])]

In [23]:
t2 = torch.cat([tensor,tensor,tensor],dim=1)

In [24]:
t2

tensor([[0.5504, 0.5260, 0.8353, 0.5505, 0.3775, 0.5504, 0.5260, 0.8353, 0.5505,
         0.3775, 0.5504, 0.5260, 0.8353, 0.5505, 0.3775],
        [0.5664, 0.6632, 0.2959, 0.2655, 0.8795, 0.5664, 0.6632, 0.2959, 0.2655,
         0.8795, 0.5664, 0.6632, 0.2959, 0.2655, 0.8795],
        [0.8190, 0.4385, 0.6086, 0.9412, 0.6157, 0.8190, 0.4385, 0.6086, 0.9412,
         0.6157, 0.8190, 0.4385, 0.6086, 0.9412, 0.6157]])

In [25]:
xamp = torch.rand(3,2)

In [26]:
xamp

tensor([[0.9235, 0.2962],
        [0.0265, 0.3883],
        [0.6800, 0.2934]])

In [27]:
t3 = torch.cat([xamp,xamp,xamp],dim=1)

In [28]:
t3

tensor([[0.9235, 0.2962, 0.9235, 0.2962, 0.9235, 0.2962],
        [0.0265, 0.3883, 0.0265, 0.3883, 0.0265, 0.3883],
        [0.6800, 0.2934, 0.6800, 0.2934, 0.6800, 0.2934]])

##

### Arithmetic Operations

In [29]:
tensor = torch.ones(2,3)

In [30]:
tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [31]:
y1 = tensor.T

In [32]:
y1

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [33]:
y2 = tensor @ tensor.T # matrix multiplication with itself

In [34]:
y2

tensor([[3., 3.],
        [3., 3.]])

In [35]:
y3 = torch.zeros(3,4)

In [36]:
y4 = tensor @ y3

In [37]:
y4

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
y5  = tensor.matmul(y3)

In [39]:
y5

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3.],
        [3., 3.]])

In [41]:
print(y1)
print(y2)
print(y3)

tensor([[3., 3.],
        [3., 3.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[3., 3.],
        [3., 3.]])


In [42]:
# element wise multiplication

tensor = torch.rand(1,2)

In [43]:
tensor

tensor([[0.1288, 0.5976]])

In [44]:
z1 = tensor * tensor

In [45]:
z1

tensor([[0.0166, 0.3572]])

In [46]:
z2 = tensor * torch.zeros(1,2)

In [47]:
z2

tensor([[0., 0.]])

## single element tensor

In [48]:
tensor = torch.ones_like(z2)

In [49]:
tensor

tensor([[1., 1.]])

In [51]:
agg = tensor.sum()

In [52]:
agg

tensor(2.)

In [53]:
agg_item = agg.item()

In [54]:
print(agg_item, type(agg.item))

2.0 <class 'builtin_function_or_method'>


### Inplace operations 
#### These are the operations which change the operand's value in place they are used by a suffix_

In [56]:
print(f"{tensor} \n")

tensor([[1., 1.]]) 



In [57]:
tensor.add_(5)

tensor([[6., 6.]])

In [58]:
print(f"{tensor} \n")

tensor([[6., 6.]]) 



#### Bridging with Numpy

In [60]:
t = torch.ones(5)
print(f"t: {t}")

t: tensor([1., 1., 1., 1., 1.])


In [61]:
n = t.numpy()
print(f"n: {n}")

n: [1. 1. 1. 1. 1.]


#### change in the tensor is reflected because the tensors in the cpu and the numpy array's are sharing the underlying memory location

In [64]:
t.add_(1)

tensor([3., 3., 3., 3., 3.])

In [65]:
n

array([3., 3., 3., 3., 3.], dtype=float32)

#### numpy array to tensor

In [66]:
import numpy as np
n = np.ones(4)

In [67]:
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1.], dtype=torch.float64)

In [73]:
np.add(n,3,out=n)

array([10., 10., 10., 10.])

In [74]:
print(f"n: {n}")

n: [10. 10. 10. 10.]


In [75]:
print(f"n: {t}")

n: tensor([10., 10., 10., 10.], dtype=torch.float64)
